### ISSUE TITLE
formal/informal

### ISSUE THREAD

**Issue by ksh** [andrewyng/translation-agent#22]
How can I specify formal/informal when using translate?

Thank you

**Comment by methanet** [comment]
@ksh Thanks for your question. The way to enforce formal/informal tone in the translation is by updating the instructions in  `reflection_prompt` (e.g. "The final style and tone of the translation should be formal/informal"). We experimented with the tone prior to releasing this demo but decided not too include the tone (e.g., formal/informal) as a function argument as it may be too specific. Feel free to modify the prompt on your end if you'd like to experiment with how the quality of the translation changes as a function of the tone specification in `reflection_prompt`.

**Comment by ksh** [comment]
Thank you!

**Comment by methanet** [comment]
@ksh closing for now, but if you. have ideas fro extending the functionality to add support for tone or other enhancements, feel free to submit a PR.
